### ISSUE TITLE
Milestone 1 Tasks

### ISSUE THREAD

**Issue by Andrew-Tan** [UBC-MDS/dsci-532_group08#1]
- Submission
   - [x] Pick a suitable licence. MIT and BSD-3 are common good options for open source projects.
   - [x] Create a release on GitHub.com before the submission deadline
   - [x] Submit `canvas-submission.md` to Canvas
- Proposal
   - [x] Motivation and Purpose - @shoebillm 
       - Target audience: Government official interested in knowing the condition of current mental health situation in tech
   - [x] Description of the data - @shoebillm 
   - [x] Research questions and usage scenarios - @Andrew-Tan 
- [x] Description of your app & sketch - @jordanlau123 @danielon-5 
- Team work contract and collaborative documentation
   - [x] Team work contract
   - [x] Code of Conduct
   - [x] Contribution guidelines - @danielon-5 
- Start developing your app (Optional) (Not going to work on this due to time constrains)

**Comment by shoebillm** [comment]
Files to be added under the repo root:

- [x] Canvas-submission.md

- [x] LICENSE

- [x] proposal.md <= 1000 words

- [x] README.md 200-300 words

- [x] team-contract.md

- [x] CODE_OF_CONDUCT.md

- [x] CONTRIBUTING.md

**Comment by Andrew-Tan** [comment]
Closing as all tasks are done.
