### ISSUE TITLE
Milestone 2 tasks

### ISSUE THREAD

**Issue by Andrew-Tan** [UBC-MDS/dsci-532_group08#10]
- [Submission](https://github.ubc.ca/MDS-2020-21/DSCI_532_milestone2_group08/blob/master/milestone2.md#1-submission-instructions)
   - [x] Create a release on GitHub.com before the submission deadline
   - [x] Submit `canvas-submission.html` to Canvas
       - [x] add a link to your milestone release in this file
- [Deployment on Heroku](https://github.ubc.ca/MDS-2020-21/DSCI_532_milestone2_group08/blob/master/milestone2.md#2-deployment-on-heroku) (**Don't wait until the last moment, deploy early and test for potential problems**)
   - [x] Deploy your app on Heroku and include the link to your deployed dashboard clearly visible near the top of your README
       - **Don't push to Heroku after the milestone deadline!!**
   - [x] Change the `Procfile` to `web: gunicorn src.app:server` instead of what it is in the dash deployment docs.
   - [x] Include `requirements.txt` (Optional, but recommended)
- [x] [Interactive Dash app in Python and Altair](https://github.ubc.ca/MDS-2020-21/DSCI_532_milestone2_group08/blob/master/milestone2.md#3-interactive-dash-app-in-python-and-altair)
   - [x] Aim to implement most of your dashboard's functionality, but not everything.
   - [x] Interface should be as self-documenting as possible, with appropriate labels for panes and widgets, legends documenting the meaning of visual encodings, and a meaningful title for the app
   - [x] Make sure the app works in a **full-screen** window
- [Reflection](https://github.ubc.ca/MDS-2020-21/DSCI_532_milestone2_group08/blob/master/milestone2.md#4-reflection)
    - [x] Document on what we have implemented in our dashboard so far
    - [x] Include what we know is not working in our dashboard (**so that TAs can distinguish between features in development and bugs**)
    - [x] Document what we think our dashboard does well what its limitations are
    - [x] Document what are good future improvements and additions
    - [x] Should **NOT** be more than 500 words and the `reflection-milestone2.md` document should live in our GitHub.com repo in the `doc` folder
- [ ] [Improve the README](https://github.ubc.ca/MDS-2020-21/DSCI_532_milestone2_group08/blob/master/milestone2.md#5-improve-the-readme-optional) (Optional)
    - Follow the link above to read the detailed instruction
