### ISSUE TITLE
Milestone 3 tasks

### ISSUE THREAD

**Issue by Andrew-Tan** [UBC-MDS/dsci-532_group08#22]
- [Submission](https://github.ubc.ca/MDS-2020-21/DSCI_532_milestone3_group08/blob/master/milestone3.md#1-submission-instructions)
   - [x] Create a new repo for this project. Name it the same as your Python dashboard repo plus a -R suffix so it is easy to find (e.g. your-previous-repo-name-R)
   - [x] Copy over your contributing guidelines, code of conduct README file, and the necessary data files
       - [x] Update your README with a link to the deployed R dashboard and a new image/gif of the R dashboard in action
   - [x] Create a release on GitHub.com before the submission deadline
   - [x] Submit `canvas-submission.html` to Canvas
       - [x] add a link to your milestone release in this file
- [Deployment on Heroku](https://github.ubc.ca/MDS-2020-21/DSCI_532_milestone3_group08/blob/master/milestone3.md#2-deployment-on-heroku) (**Don't wait until the last moment, deploy early and test for potential problems**)
   - [x] Deploy your app on Heroku and include the link to your deployed dashboard clearly visible near the top of your README
       - **Don't push to Heroku after the milestone deadline!!**
   - [x] Heroku does not have native support for R so we will need to use a docker image provided by Dash
- [Interactive Dash app with R and ggplotly](https://github.ubc.ca/MDS-2020-21/DSCI_532_milestone3_group08/blob/master/milestone3.md#3-interactive-dash-app-with-r-and-ggplotly)
   - [x] Implement the same dashboard as in milestone 2
       - Don't need to rewrangle the raw data. Use the processed data.
       - The goal is to implement most of the milestone 2 dashboard so that you can compare dashboard development in Python and R
   - [x] Address TA's feedback for Milestone 1 if possible (Can be delayed to the next milestone)
- [Reflection](https://github.ubc.ca/MDS-2020-21/DSCI_532_milestone3_group08/blob/master/milestone3.md#4-reflection)
    - [x] Document on what we have implemented in our dashboard so far
    - [x] Include what we know is not working in our dashboard (**so that TAs can distinguish between features in development and bugs**)
    - [x] Include some brief thoughts on the experience of implementing the dashboard a second time in another language. You could also mention some feedback you have received and how that has impacted your future planning
    - [x] This section should be around 300-400 words and the `reflection-milestone3.md` document should live in your GitHub.com repo in the `doc` folder
- [x] [Give peer feedback to another group](https://github.ubc.ca/MDS-2020-21/DSCI_532_milestone3_group08/blob/master/milestone3.md#5-give-peer-feedback-to-another-group-optional) (Optional)
    - Follow the link above to read the detailed instruction
