### ISSUE TITLE
Milestone 4 tasks

### ISSUE THREAD

**Issue by shoebillm** [UBC-MDS/dsci-532_group08#25]
**1. Submission**  

- [x] Canvas submission 
- [x] `canvas-submission.html`

**2. Deployment on Heroku**
- [x] Deploy on Heroku 
- [x] Deployed link on README
- [x] Set up Heroku's GitHub integration 
     - [x] New branch: `deployment`

**3. Deliver a production ready app**

- [x] Address TAs feedback from M1 and M2
- [x] Address the peer feedback 
- [x] Set the title of the browser tab 
- [x] "About" GitHub repo description 
     - [x] A short description of the app
     - [x] The link to deployed dashboard
     - [x] keywords describing plots, widgets, and interactions
 
**4. Reflection**
- [x] Reflection 

**5. Document the functions' functionality (Optional)** 

- [ ] Write proper docstrings 

**6. Set up app review with Heroku (Optional)**

- [x] Create ≥ PR that triggers an auto-deployment
- [x] Link the PR in `canvas-submission.html`
